# Generated by Django 5.1.6 on 2025-03-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.PositiveIntegerField(default=123456789),
            preserve_default=False,
        ),
    ]
